### ISSUE TITLE
build constraints exclude all Go files

### ISSUE THREAD

**Issue by neov-98** [playmixer/pc.assistent#1]
Hello, I decided to try to install it, but I encountered a problem that could not be quickly resolved.
When I launch I get this error:
```
pc.assistent> go run .
github.com/Picovoice/pvrecorder/binding/go: build constraints exclude all Go files in C:\Users\nik\go\pkg\mod\github.com\!picovoice\pvrecorder\binding\go@v1.2.2
```
`go mod tidy ` - the problem happened again
`go clean -modcache` - clearing cache didn't help

**Comment by playmixer** [comment]
Hello, Vadim-vg

This problem can occur if CGO_ENABLED is 0, try setting it to 1
command for Windows "set CGO_ENABLED=1"
